import type {Metadata} from "next";
import HomePage from "@/app/home/page";

export const metadata: Metadata = {
  title: "Home | XSELL",
  description: "Generated by create next app",
};

export default function Home() {
  return <>
    <HomePage/>
  </>;
}
